version: '3.8'

services:
  vpr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpr-dev
    ports:
      - "50051:50051"
      - "3000:3000"
    env_file:
      - .env
    environment:
      - VPR_ADDR=0.0.0.0:50051
      - RUST_LOG=vpr=debug,info
      - VPR_ENABLE_REFLECTION=true
    volumes:
      # Mount source for development (for live reload)
      # Mount the repository so cargo-watch sees the workspace
      - ./:/app:delegated
      
      # Preserve target directory to cache compiled dependencies
      - "cargo-cache:/app/target"
      
      # Mount logs directory (optional)
      - ./logs:/home/vpr/logs
      - ./patient_data:/patient_data
    networks:
      - vpr-network
    restart: unless-stopped
    # Ensure cargo runs the default binary (runs both gRPC and REST)
    command: ["/bin/sh", "-c", "cargo watch -x 'run'"]
    healthcheck:
      test: ["CMD-SHELL", "grpcurl -plaintext -H 'x-api-key: ${API_KEY}' localhost:50051 list && curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a gRPC client tool for testing
  grpcurl:
    image: fullstorydev/grpcurl:latest
    container_name: vpr-grpcurl
    networks:
      - vpr-network
    depends_on:
      - vpr
    profiles:
      - tools
    command: 
      - /bin/sh
      - -c
      - |
        echo "gRPC testing tool ready. Use:"
        echo "docker compose -f compose.dev.yml exec grpcurl grpcurl -plaintext vpr:50051 list"
        sleep infinity

networks:
  vpr-network:
    driver: bridge

volumes:
  cargo-cache:
    driver: local
  vpr-logs:
    driver: local